---
- hosts: network 
  remote_user: vagrant


  tasks:
  - copy: src=/home/vagrant/deploy/target/arachne-0.0.1-SNAPSHOT.jar dest=/home/vagrant/
  - copy: src=/home/vagrant/deploy/target/scripts/run.sh dest=/home/vagrant/
  - copy: src=/home/vagrant/deploy/target/scripts/check.sh dest=/home/vagrant/  

  - name: Creates directory
    file: path=/home/vagrant/arachne/logs state=directory recurse=yes 
  
  - name: Move project artifacts to required path
    command: "{{ item }}"
    with_items:
    - mv /home/vagrant/arachne-0.0.1-SNAPSHOT.jar /home/vagrant/arachne/
    - mv /home/vagrant/run.sh /home/vagrant/arachne 

  #Ansible script module will also copy the script to the remote
  #location before executing it.So, no need to exclusively copy
  #it to remote.
  - name: Check and kill if the java process exists
    script: /home/vagrant/deploy/target/scripts/check.sh
  
 #Ansible command module runs the command on the remote server.
 #It expects the command to be already present on the remote server.
  - name: Execute run.sh
    command: "{{ item }}"
    with_items:
    - chmod +x /home/vagrant/arachne/run.sh
    - /home/vagrant/arachne/run.sh
