---
- hosts: network 
  remote_user: vagrant

  tasks: 

  #Copy the desired jar to the remote location from the workstation server.
  - name: Copy the test jar from workstation to remote server.
    copy: src=/home/vagrant/deploy/target/arachne-test-0.0.1-SNAPSHOT.jar dest=/home/vagrant/arachne/

  #Copy the desired script to the remote location from the workstation server.
  - name: Copy the test script from workstation to remote server.
    copy: src=/home/vagrant/deploy/target/scripts/runJunitTests.sh dest=/home/vagrant/arachne/ mode=0777
  
    
  - name: Execute runJunitTests.sh
    become: true
    shell: /home/vagrant/arachne/runJunitTests.sh